name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch 
      pull-requests: write  # To create a PR from that branch
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build static site artifact
      run: |
        rm -rf dist
        mkdir -p dist
        # Copy the static site (repo root)
        cp -a index.html dist/index.html
        cp -a css dist/css
        cp -a js dist/js
        cp -a img dist/img
        cp -a content dist/content
        # Keep custom domain
        cp -a CNAME dist/CNAME

    - name: Deploy GitHub Pages
      run: |
        git worktree add gh-pages
        git config user.name "Deploy from CI"
        git config user.email ""
        cd gh-pages
        # Delete the ref to avoid keeping history.
        git update-ref -d refs/heads/gh-pages
        rm -rf *
        mv ../dist/* .
        git add .
        git commit -m "Deploy $GITHUB_SHA to gh-pages"
        git push --force --set-upstream origin gh-pages
